### ISSUE TITLE
CPU temp shown as NA on Pi 4

### ISSUE THREAD

**Issue by Pythonic456** [KrispyCamel4u/SysMonTask#107]
https://github.com/Botspot/pi-apps/issues/1611#issue-1174044530

Happy to provide extra info if necessary.

**Comment by theofficialgman** [comment]
duplicate of : https://github.com/KrispyCamel4u/SysMonTask/issues/102 and https://github.com/KrispyCamel4u/SysMonTask/issues/91

known issue by the dev

**Comment by Pythonic456** [comment]
Ok. Because it's mostly Python code I will implement my own fix. Thanks!
