### ISSUE TITLE
Not working on Manjaro

### ISSUE THREAD

**Issue by reloadedd** [KrispyCamel4u/SysMonTask#11]
I tried installing with the basic `sudo python3 ./setup.py install`.

First error I've got when running `sysmontask` was that the files from the `glade_files/` directory weren't copied to `/usr/share/sysmontask`. This was solved using: `sudo mkdir /usr/share/sysmontask/ && sudo cp -r glade_files/ /usr/share/sysmontask/`.

The next error was about the interpreter complaining that the `mem` module wasn't installed, which then I've installed (`sudo pip3 install mem`). 

The final error which I couldn't solve was about the `sidepane` module which was not installed, but sadly 'No matching distribution found for sidepane'.

My system:
```shell
Linux Hades 5.11.0-1-MANJARO #1 SMP PREEMPT Mon Feb 8 07:36:52 UTC 2021 x86_64 GNU/Linux
```
EDIT: Added the traceback.
```shell
[sudo] password for reloadedd: acquired root permission
/usr/lib/python3.9/site-packages/sysmontask-1.1.1-py3.9.egg/sysmontask/sysmontask.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sysmontask-1.1.1-py3.9.egg/sysmontask/sysmontask.py", line 28, in <module>
    from sidepane import *
ModuleNotFoundError: No module named 'sidepane'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.1.1', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask-1.1.1-py3.9.egg/sysmontask/sysmontask.py", line 39, in <module>
    from sysmontask.disk import *
  File "/usr/lib/python3.9/site-packages/sysmontask-1.1.1-py3.9.egg/sysmontask/disk.py", line 17, in <module>
    from sysmontask.proc import sorting_func,byte_to_human
  File "/usr/lib/python3.9/site-packages/sysmontask-1.1.1-py3.9.egg/sysmontask/proc.py", line 1, in <module>
    from gi.repository import Gtk as g , GLib as go,GdkPixbuf,Wnck, Gio
  File "/usr/lib/python3.9/site-packages/gi/importer.py", line 131, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Wnck, introspection typelib not found
```

Thank you for your time.

**Comment by KrispyCamel4u** [comment]
Hi,
Installation from the source probably won't work. I am yet to do that. But you can run it directly by cloning the repo and installing the required dependencies. 
I will resolve it as soon as possible. Till then, please wait or directly run from the source.

**Comment by reloadedd** [comment]
> Hi,
> Installation from the source probably won't work. I am yet to do that. But you can run it directly by cloning the repo and installing the required dependencies.
> I will resolve it as soon as possible. Till then, please wait or directly run from the source.

Okay. Thank you!

**Comment by yochananmarqos** [comment]
@reloadedd Try this PKBUILD:

```
pkgname=sysmontask
_gitname=SysMonTask
pkgver=1.1.1_beta
pkgrel=1
pkgdesc="System Monitor With UI Like Windows"
arch=('any')
url="https://github.com/KrispyCamel4u/SysMonTask"
license=('MIT')
depends=('python' 'python-psutil>=5.8' 'python-gobject' 'python-cairo'
         'libwnck3' 'gtk3' 'zenity')
makedepends=('python-setuptools')
source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")
sha256sums=('d7d184678886e46efc51ea2c890e0496c0871e0674b804dc4b3cb2027a74f13b')

build() {
	cd "$_gitname-$pkgver"
	python setup.py build
}

package() {
	cd "$_gitname-$pkgver"
	export PYTHONHASHSEED=0
	python setup.py install --root="$pkgdir" --optimize=1 --skip-build

	install -d "$pkgdir/usr/share/licenses/$pkgname"
	mv "$pkgdir/usr/share/doc/$pkgname/LICENSE" \
		"$pkgdir/usr/share/licenses/$pkgname"
}
```

**Comment by KrispyCamel4u** [comment]
Hi, 
Someone has already made an AUR package for it and it gets installed fine.  some changes for Manjaro(process tab) and support for other desktop environments will be made to the source soon.
[https://aur.archlinux.org/packages/sysmontask/](url)

**Comment by yochananmarqos** [comment]
@KrispyCamel4u: Yes, I'm the Co-Maintainer. I just updated it with that PKGBUILD yesterday. :wink:

**Comment by KrispyCamel4u** [comment]
> @KrispyCamel4u: Yes, I'm now the Co-Maintainer. I just updated it with that PKGBUILD yesterday. wink

Hello, Thank you very much. Can you tell me your name, email so that I can include the packager's details in the AUTHORS.md?
Please contact me by mail.

**Comment by yochananmarqos** [comment]
It's right there at the top of the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sysmontask) and on my [profile](https://aur.archlinux.org/account/yochananmarqos).

**Comment by KrispyCamel4u** [comment]
Yup, got it.
