### ISSUE TITLE
Processes missing from process tab

### ISSUE THREAD

**Issue by UserBlackBox** [KrispyCamel4u/SysMonTask#15]
![image](https://user-images.githubusercontent.com/36890802/109702503-52237900-7b62-11eb-9c5c-5359c7c1382f.png)

SysMonTask is missing a large amount of processes between PID 1644-105090 and past 105482. I am running the program on Arch Linux using the AUR package but I have tried just running from source. I am using Python 3.9.2. Most of my desktop processes are running at PIDs 1679-2863 including Discord, Firefox, and Thunderbird which don't show up.

**Comment by whatistime** [comment]
I'm running Mint 20.04, and I'm missing tons of processes too.

![image](https://user-images.githubusercontent.com/26552362/109760882-5a9ca380-7ba4-11eb-906d-e39e852c863e.png)


The other issue I have is getting any updates from my hardware in the performance tab, I've had the program open for 10 minutes now, and this is all I have.
![image](https://user-images.githubusercontent.com/26552362/109761158-c979fc80-7ba4-11eb-8781-702d7797a00b.png)

**Comment by RDKRACZ** [comment]
It's missing tons of processes for me too. Commenting to get updates.

**Comment by KrispyCamel4u** [comment]
> 
> 
> I'm running Mint 20.04, and I'm missing tons of processes too.
> 
> ![image](https://user-images.githubusercontent.com/26552362/109760882-5a9ca380-7ba4-11eb-906d-e39e852c863e.png)
> 
> The other issue I have is getting any updates from my hardware in the performance tab, I've had the program open for 10 minutes now, and this is all I have.
> ![image](https://user-images.githubusercontent.com/26552362/109761158-c979fc80-7ba4-11eb-8781-702d7797a00b.png)

can you share the output when run from terminal:
```
$ sysmontask
```

**Comment by whatistime** [comment]
I rebooted, and I can see things on the performance tab.  Here is my output: 

[sudo] password for caterpillar: acquired root permission
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
/usr/lib/python3/dist-packages/sysmontask/proc.py:1: PyGIWarning: Wnck was imported without specifying a version first. Use gi.require_version('Wnck', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go,GdkPixbuf,Wnck, Gio

(sysmontask:743909): Gtk-WARNING **: 22:47:23.880: Could not load image 'usr/share/sysmontask/icons/SysMonTask.png': Failed to open file “/usr/share/sysmontask/glade_files/usr/share/sysmontask/icons/SysMonTask.png”: No such file or directory
memory tab initialising
sda
sdb
no nvidia gpu found
update Dir right True
update speed to normal
initialisating sidepane
hello
quit from menu quit
quit from menu quit

**Comment by KrispyCamel4u** [comment]
Hi,
I have added the support for cinnamon and xfce desktop environments you can update to the latest one. Let me know about it.

**Comment by UserBlackBox** [comment]
I'm using i3wm and was just wondering is there any solution to this issue that isn't desktop environment specific?

**Comment by KrispyCamel4u** [comment]
> I'm using i3wm and was just wondering is there any solution to this issue that isn't desktop environment specific?

Hi,
I am currently working on doing that, using a filter, the user can define words/regex expressions to filter out processes that he doesn't care about which will be platform-independent.

**Comment by RDKRACZ** [comment]
Tried on a different system (Kubuntu) and it's displaying only a few processes.

**Comment by KrispyCamel4u** [comment]
> Tried on a different system (Kubuntu) and it's displaying only a few processes.

Hmm, it is lacking KDE support, the next release will use a more general approach where the user can define his/her filtering words instead of hardcoding them for a specific Desktop env.

**Comment by HanM23** [comment]
Hello,
Thanks for this app, i love it.
 Nevertheless, here is what i get (I use Manjaro + XFCE + installed SysMonTask from AUR with pamac GUI)

**1) If i run it via my user account (non root)**
![Screenshot_2021-03-16_15-23-18](https://user-images.githubusercontent.com/38059479/111326293-ba974d80-866c-11eb-8c2a-4f6907abfda0.png)


A lot of processes are missing. For instance, when i took this screenshot i had 3 instances of xfce4-terminal running.

**2) If i run it as root with sudo i get the following error message :**
```[sudo] password for alexis:           
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask===1.1.1-beta-b', 'console_scripts', 'sysmontask')())
  File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 71, in <module>
    session_index=session_finder()
  File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 47, in session_finder
    sess=os.environ.get("DESKTOP_SESSION").lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Thank you

**Comment by KrispyCamel4u** [comment]
> Hello,
> Thanks for this app, i love it.
> Nevertheless, here is what i get (I use Manjaro + XFCE + installed SysMonTask from AUR with pamac GUI)
> 
> **1) If i run it via my user account (non root)**
> ![Screenshot_2021-03-16_15-23-18](https://user-images.githubusercontent.com/38059479/111326293-ba974d80-866c-11eb-8c2a-4f6907abfda0.png)
> 
> A lot of processes are missing. For instance, when i took this screenshot i had 3 instances of xfce4-terminal running.
> 
> **2) If i run it as root with sudo i get the following error message :**
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/sysmontask", line 33, in <module>
>     sys.exit(load_entry_point('sysmontask===1.1.1-beta-b', 'console_scripts', 'sysmontask')())
>   File "/usr/bin/sysmontask", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 71, in <module>
>     session_index=session_finder()
>   File "/usr/lib/python3.9/site-packages/sysmontask/sysmontask.py", line 47, in session_finder
>     sess=os.environ.get("DESKTOP_SESSION").lower()
> AttributeError: 'NoneType' object has no attribute 'lower'
> ```
> 
> Thank you

Hi
Thank you for this.
Can you share the details of three env variables namely: $DESKTOP_SESSION, $XDG_SESSION_DESKTOP, $XDG_CURRENT_DESKTOP, since I am suspecting that the detection of xfce4 is not happening as it should. After that I am might be able to help you out with a quick fix :)

**Comment by HanM23** [comment]
Sure, here is what i get 
```
$ echo $DESKTOP_SESSION $XDG_SESSION_DESKTOP $XDG_CURRENT_DESKTOP
xfce xfce XFCE
```

**Comment by KrispyCamel4u** [comment]
Hmm, got it. For the quick fix please replace the content of the sysmontask.py file in /usr/lib/python\<version\>/dist-package/sysmontask/ to the file attached or you can copy it from the file in repo I have fixed that in the master branch. It will solve the issue.

[sysmontask.txt](https://github.com/KrispyCamel4u/SysMonTask/files/6153706/sysmontask.txt)

**Comment by HanM23** [comment]
> Hmm, got it. For the quick fix please replace the content of the sysmontask.py file in /usr/lib/python<version>/dist-package/sysmontask/ to the file attached or you can copy it from the file in repo I have fixed that in the master branch. It will solve the issue.
> 
> [sysmontask.txt](https://github.com/KrispyCamel4u/SysMonTask/files/6153706/sysmontask.txt)

That's perfect now ! Thanks a lot :)

**Comment by pawlosck** [comment]
I have the same problem under Ubuntu 20.10 and KDE.
I downloaded this file and this doesn't work too.
I have message
_warning[critical]: psutil>=5.7.3 needed(system-wide)_
In Ubuntu 20.10 is 5.7.2.

**Comment by KrispyCamel4u** [comment]
> I have the same problem under Ubuntu 20.10 and KDE.
> I downloaded this file and this doesn't work too.
> I have message
> _warning[critical]: psutil>=5.7.3 needed(system-wide)_
> In Ubuntu 20.10 is 5.7.2.

Hi, Can you get the full log of error after running from the terminal?

**Comment by pawlosck** [comment]
I put file sysmontask.txt into /usr/lib/python3/dist-packages/sysmontask (renamed from sysmontask.txt to sysmontask.py)

Without sudo:

warning[critical]: psutil>=5.7.3 needed(system-wide)
0
memory tab initialising
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
Failed to get Memory Form Factor
nvme0n1
/bin/sh: 1: nvidia-smi: not found
no nvidia gpu found
update Dir right True
update speed to normal
initialisating sidepane
hello
print with cancel



With sudo
warning[critical]: psutil>=5.7.3 needed(system-wide)
0
memory tab initialising
nvme0n1
/bin/sh: 1: nvidia-smi: not found
no nvidia gpu found
update Dir right True
update speed to normal
initialisating sidepane
hello
print with cancel

**Comment by KrispyCamel4u** [comment]
> I put file sysmontask.txt into /usr/lib/python3/dist-packages/sysmontask (renamed from sysmontask.txt to sysmontask.py)
> 
> **Without sudo:**
> warning[critical]: psutil>=5.7.3 needed(system-wide)
> 0
> memory tab initialising
> /sys/firmware/dmi/tables/smbios_entry_point: Permission denied
> /dev/mem: Permission denied
> /sys/firmware/dmi/tables/smbios_entry_point: Permission denied
> /dev/mem: Permission denied
> Failed to get Memory Form Factor
> nvme0n1
> /bin/sh: 1: nvidia-smi: not found
> no nvidia gpu found
> update Dir right True
> update speed to normal
> initialisating sidepane
> hello
> print with cancel
> 
> **With sudo**
> warning[critical]: psutil>=5.7.3 needed(system-wide)
> 0
> memory tab initialising
> nvme0n1
> /bin/sh: 1: nvidia-smi: not found
> no nvidia gpu found
> update Dir right True
> update speed to normal
> initialisating sidepane
> hello
> print with cancel

Hi 
So if the processes are no shown properly it is because kde support as of now not present. You have to wait for the next release.

**Comment by KrispyCamel4u** [comment]
Hi,
A new version is out and finally using Filter Dialog, the process tab works on all. Now the processes are not filtered already but can be configured depending upon Destro and Desktop Environments. 
Also, some overall modifications and new features have been added, check out readme to know more.

Let me know the issues regarding the same and also suggestions are most welcomed.

**Comment by UserBlackBox** [comment]
Seems to work perfectly on i3wm

**Comment by pawlosck** [comment]
KDE Plasma (Ubuntu 20.10) -> looks good

**Comment by KrispyCamel4u** [comment]
To remove the unnecessary processes from the process tab view use the view->Filter. Read more on that in [docs](https://github.com/KrispyCamel4u/SysMonTask/blob/master/DOCS.md#filter-dialog-view-filter)
