### ISSUE TITLE
psutils version fallbac

### ISSUE THREAD

**Issue by oumar17** [KrispyCamel4u/SysMonTask#16]
While installing on Ubuntu 20.04 using 'apt install', python3-psutil (5.5.1-1ubuntu4) is automatically installed even though running "sudo pip3 install -U psutil" would install v5.8 and the former version is used, while it is less than the required version as it is specified in dependencies. Running the app using terminal produce a lot of error, sometime no sys data, sometime crashes.

**Comment by oumar17** [comment]
While installing on Ubuntu 20.04 using 'apt install', python3-psutil (5.5.1-1ubuntu4) is automatically installed even though running "sudo pip3 install -U psutil" would install v5.8 and the former version  is used, while it is less than the required version as it is specified in dependencies. Running the app using terminal produce a lot of error, sometime no sys data, sometime crashes.

**Comment by KrispyCamel4u** [comment]
For ubuntu<=20.04 i have removed it from the dependencies so that is is not automatically installed. You have to install psutil separately, for 20.10 it is automatically installed.
