### ISSUE TITLE
psutil>=5.7.3 needed(system-wide)

### ISSUE THREAD

**Issue by douglasfl** [KrispyCamel4u/SysMonTask#18]
Hi,
on ElementaryOS 5.1.7 when open app, it say:
psutil>=5.7.3 needed(system-wide)

**Comment by KrispyCamel4u** [comment]
Hi, 
[Read more](https://github.com/KrispyCamel4u/SysMonTask/blob/master/README.md) for the issue.
The process tab will not  show much info, unless it is like gnome desktop environment. Support is being added up.
