### ISSUE TITLE
Does not work en PopOs 20.10

### ISSUE THREAD

**Issue by LaBaude32** [KrispyCamel4u/SysMonTask#23]
When you click on the icon, a window opens and asks for your password. When you validate, the window disappears, that's all.

**Comment by KrispyCamel4u** [comment]
Hi,
Can you run it from the terminal:
```
$ sysmontask
```
and share the output?

**Comment by KrispyCamel4u** [comment]
Hi,
Can you update me regarding the issue?

**Comment by CaLouro** [comment]
Hey, same issue here. Can't launch the app through the icon. It opens it via terminal but it doesn't refresh and has some warnings.

Also, I wasn't able to change the app's theme. Ran the command but it opened on the default theme.

```bash
caio@pop-os:~$ sudo sysmontask
acquired root permission
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
/usr/lib/python3/dist-packages/sysmontask/proc.py:1: PyGIWarning: Wnck was imported without specifying a version first. Use gi.require_version('Wnck', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go,GdkPixbuf,Wnck, Gio

(sysmontask:16811): Gtk-WARNING **: 11:40:41.357: Could not load image 'usr/share/sysmontask/icons/SysMonTask.png': Failed to open file “/usr/share/sysmontask/glade_files/usr/share/sysmontask/icons/SysMonTask.png”: No such file or directory
memory tab initialising
sda
sdb
okk
update Dir right True
update speed to normal
initialisating sidepane
hello
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 465, in updater
    self.gpuTabUpdate()
  File "/usr/lib/python3/dist-packages/sysmontask/gpu.py", line 369, in gpuUpdate
    self.gpuEncodingArray.append(int(gpuinfoRoot.find('gpu').find('utilization').find('encoder_util').text[:-1]))
ValueError: invalid literal for int() with base 10: 'N/'
poping 16728
```

I love the idea. The only thing Windows does better than Linux is the Task Manager and this project is awesome.

**Comment by KrispyCamel4u** [comment]
Hi,
Thanks got the bug and it has been fixed also, I have to make some other changes and I will release a new one as soon as possible.

**Comment by CaLouro** [comment]
That was a quick fix. You have my thanks, friend.

**Comment by LaBaude32** [comment]
> Hi,
> Can you run it from the terminal:
> 
> ```
> $ sysmontask
> ```
> 
> and share the output?

Hi,

Without sudo, I have the same issue : a new window is opening asking my password, I use it and clic on accept then the window shut down and nothing more.

If i use sudo i got that : 
```acquired root permission
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
```
and the new windows show me : 

> psutil>=5.7.3 needed(system-wide)

**Comment by CaLouro** [comment]
@LaBaude32 the readme says that for the `psutil>=5.7.3 needed(system-wide)` error you need to run `sudo pip3 install -U psutil` to update psutils

**Comment by CaLouro** [comment]
Hey @KrispyCamel4u, on the latest beta release, this seem to have been fixed. Thanks for the support. This issue could be closed I think.
