### ISSUE TITLE
Wrong arrows direction on Processes tabs

### ISSUE THREAD

**Issue by dariuszt** [KrispyCamel4u/SysMonTask#26]
Hi,

I think the arrows (little triangles) on User Processes section (like in attachment: green is like it should be (from System Monitor), red is wrong direction) should be the opposite way.
When sorting is set from highest to lowest, the triangle should point down and for lowest to highest, should be pointing up.
![sysmontask_arrows](https://user-images.githubusercontent.com/49672676/110130840-c3b13080-7dc9-11eb-9415-134c77a8b386.png)

**Comment by KrispyCamel4u** [comment]
Hi,
Thanks for pointing it out. It will be fixed next release.

**Comment by KrispyCamel4u** [comment]
This has been fixed in the latest release.
