### ISSUE TITLE
How to search or filter for processes

### ISSUE THREAD

**Issue by gggirlgeek** [KrispyCamel4u/SysMonTask#27]
Hello,
I'd like to know if you can add a feature to search for a process. It would need to also find any child processes or services, and include searching within the path and/or, maybe, command, not just the process name. When using ProcessHacker for Windows this feature is indispensable because it allows me to find all the services and processes related to the program I am researching. For example, Easeus has a service named Agent.exe and a Window named Launcher.exe. They all come up when I filter for Easeus. Also, how do I get sysmonTask to display processes for all users?

As a side note, I love this app because it shows the real memory being used by the program, unlike most of the competition. Thank you!

**Comment by KrispyCamel4u** [comment]
Hi,
Thank you so much.
As far as the process tab is concerned I am working on adding support for different desktop environments. I will surely include search in near future. 
And if you are using Ubuntu or Linux with gnome desktop env then it should include processes for all users. 
If you can share respective details(process tab screenshot, sysmontask terminal output, os etc) it would help in debugging and fixing the bug.

**Comment by gggirlgeek** [comment]
Mine says "User Processes" at the top.

I am on Ubuntu Mate.

Would it help to run from a root account?

**Comment by KrispyCamel4u** [comment]
Hi, 
Unless you are using fakeroot it will run with root privilege only. And my bad, by ubuntu actually I was also meaning the default gnome one. 
Since you're using Mate, that will not work well as you would expect. Give me some time, I am adding the support, until please wait for that.

**Comment by gggirlgeek** [comment]
Thank you. For my education, can you explain to me the difference in how Mate handles permissions and Gnome or XCFE (on Ubuntu 20.04)? Or point me to a website? I am working on this very problem right now on a VPS and didn't realize there was a difference. I thought permissions was a global Ubuntu/Debian thing -- maybe even Linux Kernel.

**Comment by KrispyCamel4u** [comment]
Permission for specific usage might be different (have not experienced any). But as far my work with permission involved use of polkit or policykit which I think is used by almost all major destros.  You might wanna check out these links:
[https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-security-policykit.html]()
[https://www.freedesktop.org/software/polkit/docs/0.105/polkit-apps.html](url)

**Comment by KrispyCamel4u** [comment]
Hi,
The new version is out, it includes the searching facility.
Also, many other modification and new features have been added check out in readme to know more.

Let me know if you still face the issue.

**Comment by gggirlgeek** [comment]
Oh, cool! Thanks.
