### ISSUE TITLE
No module named 'sysmontask.mem'; 'sysmontask' is not a package

### ISSUE THREAD

**Issue by lazyprog** [KrispyCamel4u/SysMonTask#33]
Hi! 

After clone repo, run directly 
SysMonTask/sysmontask/sysmontask.py 

see this:

```
Traceback (most recent call last):
  File "SysMonTask/sysmontask/sysmontask.py", line 37, in <module>
    from sysmontask.mem import *
  File "/home/user/SysMonTask/sysmontask/sysmontask.py", line 37, in <module>
    from sysmontask.mem import *
ModuleNotFoundError: No module named 'sysmontask.mem'; 'sysmontask' is not a package

```
sudo  SysMonTask/sysmontask/sysmontask.py - get the same...

OS: Ubuntu 20.04.2 LTS x86_64
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux

Thanks for your time!

**Comment by ObaraEmmanuel** [comment]
Run from inside the root directory  `~/SysMonTask/`  not outside so that `sysmontask` module is added to `sys.path` automatically.

**Comment by KrispyCamel4u** [comment]
> Hi!
> 
> After clone repo, run directly
> SysMonTask/sysmontask/sysmontask.py
> 
> see this:
> 
> ```
> Traceback (most recent call last):
>   File "SysMonTask/sysmontask/sysmontask.py", line 37, in <module>
>     from sysmontask.mem import *
>   File "/home/user/SysMonTask/sysmontask/sysmontask.py", line 37, in <module>
>     from sysmontask.mem import *
> ModuleNotFoundError: No module named 'sysmontask.mem'; 'sysmontask' is not a package
> ```
> 
> sudo SysMonTask/sysmontask/sysmontask.py - get the same...
> 
> OS: Ubuntu 20.04.2 LTS x86_64
> Python 3.8.5 (default, Jan 27 2021, 15:41:15)
> [GCC 9.3.0] on linux
> 
> Thanks for your time!

Hi,
Do you still have this issue?

**Comment by KrispyCamel4u** [comment]
Since no update has been given regarding the issue, I will close this now. In any case you can open it again.
