### ISSUE TITLE
Invalid version (double separator '-'): 1.1.1-beta-b: python3dist(sysmontask) = 1.1.1-beta-b

### ISSUE THREAD

**Issue by tim77** [KrispyCamel4u/SysMonTask#34]
```
RPM build errors:
    Invalid version (double separator '-'): 1.1.1-beta-b: python3.9dist(sysmontask) = 1.1.1-beta-b
    Invalid version (double separator '-'): 1.1.1-beta-b: python3dist(sysmontask) = 1.1.1-beta-b
```

Hello. Can't package this awesome app because of such little thing and RPM consider this as error. Please refuse to use such 
custom suffixes and non-canonical tag versions and stick with [semver](https://semver.org/).

**Comment by KrispyCamel4u** [comment]
Hi,
Is this due to the version name defined in setup.py?
For building the package is it like you are cloning the repo and building or the build process directly use the repo URL?
Or is do I have to change on my side to properly work this out?

**Comment by tim77** [comment]
> Is this due to the version name defined in setup.py?

The problem comes from here https://github.com/KrispyCamel4u/SysMonTask/blob/master/setup.py#L15

If we replace `'1.1.1-beta-b'` -> `'1.1.1-beta.b'` for example then it's Okay and no error during build.

I guess this RPM specific error due to autogenerators and such.

**Comment by KrispyCamel4u** [comment]
So it depends on the changes on the git repo right?
If that is the case I will make changes to the repo.

**Comment by tim77** [comment]
Yep. If we could have instead of `1.1.1-beta-b` something like `1.1.1-beta2` in `setup.py` then no problem and seems like this correct way for versioning for such pre-releases according to semver.

**Comment by KrispyCamel4u** [comment]
>  Is this due to the version name defined in setup.py?
> 
> The problem comes from here https://github.com/KrispyCamel4u/SysMonTask/blob/master/setup.py#L15
> 
I have changed it from ```1.1.1-beta-b``` to ```1.1.1-beta2```
