### ISSUE TITLE
Lil spelling error

### ISSUE THREAD

**Issue by RDKRACZ** [KrispyCamel4u/SysMonTask#37]
![image](https://user-images.githubusercontent.com/43277609/111065934-a3b1f900-84bc-11eb-80f2-30f5e7c89b4f.png)

**Comment by KrispyCamel4u** [comment]
Hi, 
I am guessing, is this screen the comes when trying to install from the .deb package file? If so, I tried doing that and didn't fount this. I also checked the files, all are looking good. Can you share your OS details, I will try to regenerate it on VM in that case.

**Comment by RDKRACZ** [comment]
Yes,
OS: Kubuntu 20.10 x86_64 
Kernel: 5.8.0-44-generic 
Resolution: 3440x1440 
DE: Plasma 5.19.5 
WM: KWin 
WM Theme: Breeze 
Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: NVIDIA GeForce GTX 1070 
Memory: 25555MiB / 32063MiB

**Comment by RDKRACZ** [comment]
This is an issue with Qapt app, confirmed by using Gdebi. Sadly I don't know where can I report them this.
