### ISSUE TITLE
Can't click on the tabs in the performance tabs.

### ISSUE THREAD

**Issue by RDKRACZ** [KrispyCamel4u/SysMonTask#38]
![image](https://user-images.githubusercontent.com/43277609/111065998-0b684400-84bd-11eb-8b37-4928d929c45d.png)

**Comment by KrispyCamel4u** [comment]
They don't support clicking, to change the tab at the top, a stack switcher is used.
After all compatibility and major bugs are fixed, I will look into making it clickable.

**Comment by jgardiner68** [comment]
Being able to click on the Performance entries on the left would be more intuitive than using the tabs on the top.  A small change and a big improvement

**Comment by KrispyCamel4u** [comment]
> Being able to click on the Performance entries on the left would be more intuitive than using the tabs on the top. A small change and a big improvement

Hmm I know but the preference is given to bug fixing and making it work for all destro.

**Comment by KrispyCamel4u** [comment]
Hi,
The new version is out and now you can click on sidepane graphs and also a couple of other useful features check out readme to know more.
Let me know if you still face this issue or not.
