### ISSUE TITLE
Why SySMonTask show me only 5.7GiB instead of 8 GiB RAM on my computer?

### ISSUE THREAD

**Issue by SUPERustam** [KrispyCamel4u/SysMonTask#44]
Hello,
Maybe i noob, but why sysmontask doesn't show me all 8Gib of RAM? I think this small bug and don't really matter spoil my UX)))

My computer setup:
General OS: Manjaro Linux (native, not VM) on first physical disk (Sysmontask on this system)
Second OS: Windows 10 (native, not VM) on second physical disk
RAM: one item of 8Gib RAM
CPU: AMD Ryzen 5 2400g
Download sysmontask via "add/remove software" :
![image](https://user-images.githubusercontent.com/64551202/113484661-2d4c5980-94b2-11eb-97f0-ad64beb3b57c.png)

As a side note, I love this app because it shows app's usage cpu/ram.
Thank you!
![image](https://user-images.githubusercontent.com/64551202/113484429-e6aa2f80-94b0-11eb-8f79-66c25e50fe86.png)

**Comment by RDKRACZ** [comment]
Hmm for me it reports correct (31.3 GiB). Can you show us your `free -m` output?

**Comment by KrispyCamel4u** [comment]
Hi,
It uses psutil for data. Can  you verify the psutil version>=5.7.3 using python:
```
>>> import psutil
>>> psutil.__version__
>>> psutil.virtual_memory()  # output of this will be helpful.
```
Also output of any memory related command as mentioned by @RDKRACZ  might also be helpful.

**Comment by SUPERustam** [comment]
Thank you @RDKRACZ @KrispyCamel4u !
![Screenshot from 2021-04-04 16-11-44](https://user-images.githubusercontent.com/64551202/113509897-a609ef00-9560-11eb-8e6e-3b14ff1ea869.png)
![Screenshot from 2021-04-04 16-12-36](https://user-images.githubusercontent.com/64551202/113509898-a6a28580-9560-11eb-96b0-91f327a249b5.png)
