### ISSUE TITLE
Not working on ubuntu 20.04 (missing command from the tutorial)

### ISSUE THREAD

**Issue by emersonnevesjr** [KrispyCamel4u/SysMonTask#48]
Hey there, tried installing with apt and with the .deb file, wont work.

Did some research and checked that on ubuntu 20.04, you need to install python for pip3 before using it.

sudo apt-get install python3-pip

Please update the tutorial.

Great tool, keep the good work.

**Comment by KrispyCamel4u** [comment]
Hi, can you verify and let me know the version that you are using.?
 For v1.3.9 pip is not necessary. In case where psutil(python3-psutil) doesn't meet the version requirements, which is the case for Ubuntu<=20.04 (official repos doesn't have python3-psutil>=5.7.2), you have to install psutill via pip only.

This is mentioned in the readme under ubuntu installation. Please check out readme.
In any case please let me know.

**Comment by emersonnevesjr** [comment]
I'm using lastest version 1.3.9, that's exactly as you say, i had to manual install pip to install psutil after that, after that it worked (i tried the apt install and the .deb installer).

On the guide you say to use pip3, but first you need to install pip3, that's what i'm saying.

Just add the like to install pip3 before using it: sudo apt-get install python3-pip


![image](https://user-images.githubusercontent.com/67134746/115972384-619cbe00-a524-11eb-8567-f48393f65d57.png)

**Comment by KrispyCamel4u** [comment]
Hmm, I have added it so that people who are not familiar with pip can install it.
