### ISSUE TITLE
Charts are shifting from wrong side

### ISSUE THREAD

**Issue by j123b567** [KrispyCamel4u/SysMonTask#5]
Charts are shifting from left to right, which is uncommon.

All scopes, performance monitors, ... are moving charts from right to left (add new value to the right)

**Comment by KrispyCamel4u** [comment]
Hi, 
This has already been implemented in v1.1.1-beta. From the menu via view->graph_direction this setting can be changed.
In case you have any doubts, let me know.

**Comment by j123b567** [comment]
I have just tried the master branch expecting it to be the latest version, so if it is fixed, then it can be closed.

I just don't understand the configuration ability at all.
In all LTR languages, X axes has bigger values on the right so time goes from left (old) to right (new)
To my knowledge, in RTL languages like Arabic or Hebrew, dispite they are writing in the direction from the right to the left, they also dipicts "X" axes lower values on the left and bigger values on the right.

I'm just curious if there is any nationality understanding it differently.

If so, it should be easy to detect this from `LANG` (or similar) environemnt variable so there is no need to configure it at all.

**Comment by KrispyCamel4u** [comment]
My bad, I was working on a different branch so forgot to update it. 
And having newer on left and newer on right is actually just personal. It doesn't have any serious reason as such : )
