### ISSUE TITLE
Ability to change colors of tabs borders and graph

### ISSUE THREAD

**Issue by RDKRACZ** [KrispyCamel4u/SysMonTask#50]
The current colors are great but since this is a Linux app it should be fully configurable (prefferably from GUI)

From gnome system monitor
![image](https://user-images.githubusercontent.com/43277609/116561357-87e6a300-a902-11eb-80dc-09abc346bbe4.png)

**Comment by KrispyCamel4u** [comment]
It's been a long time, but this feature is now available in v1.x.x
