### ISSUE TITLE
Unneeded column name.

### ISSUE THREAD

**Issue by RDKRACZ** [KrispyCamel4u/SysMonTask#56]
The "Processes" is kinda duplicated here.

Cropped
<details>

![Zrzut ekranu z 2021-05-04 13-29-53](https://user-images.githubusercontent.com/43277609/116997344-f64dab80-acdc-11eb-9936-136b25b64468.png)
</details>

Full ss
<details>

![Zrzut ekranu z 2021-05-04 13-38-21](https://user-images.githubusercontent.com/43277609/116998146-116ceb00-acde-11eb-9067-9a9e19176bfd.png)
</details>

To make this possible the search box could go one bar upper.

**Comment by RDKRACZ** [comment]
This issue is an alternative to the #57

**Comment by KrispyCamel4u** [comment]
Hi,
The original use of this label was to make user and background processes but since now the user processes not a thing to consider this could be removed. Thanks for the suggestion.

**Comment by KrispyCamel4u** [comment]
This has now been changed.
