### ISSUE TITLE
Running it with superuser permission doesn't use the right theme

### ISSUE THREAD

**Issue by Danny3** [KrispyCamel4u/SysMonTask#58]
Hello!
I've tested latest version of SysmonTask (1.3.9) both normally (from desktop icon) and with superuser permission (with sudo from command line) on the latest version of Kubuntu (21.04) and I've noticed that when running with sudo the dark theme is not selected automatically like the version that I'm opening from the icon.

I'm using Breeze Dark theme that comes with Kubuntu but normally not used by default.

Could you please have a look why this this is happening ?
Or, is it possible to start the program from the desktop icon, with superuser permission (like with sudo from command line), but in a way that it doesn't request my password, but still have the dark theme and also all the necessary permissions ?

**Comment by KrispyCamel4u** [comment]
> Hello!
> I've tested latest version of SysmonTask (1.3.9) both normally (from desktop icon) and with superuser permission (with sudo from command line) on the latest version of Kubuntu (21.04) and I've noticed that when running with sudo the dark theme is not selected automatically like the version that I'm opening from the icon.
> 
> I'm using Breeze Dark theme that comes with Kubuntu but normally not used by default.
> 
> Could you please have a look why this this is happening ?
> Or, is it possible to start the program from the desktop icon, with superuser permission (like with sudo from command line), but in a way that it doesn't request my password, but still have the dark theme and also all the necessary permissions ?

Hi, 
That might be because the theme settings are not carried with the root user since both have different environments variables.
Did you try the theme setting API of sysmontask? You can find out about it in [readme](https://github.com/KrispyCamel4u/SysMonTask#theme-settings)
Let me know if it work for you.

**Comment by KrispyCamel4u** [comment]
Can you update me regarding the issue if you still have it?

**Comment by Danny3** [comment]
Tried this:
sudo sysmontask.set_dark
Index for Corresponding Theme that you want to apply?:0
Failed to set Theme:( 
Run with sudo(root privileges) is required.


Tried the same command again because I didn't see it asking for my password before and looked like it worked:
Index for Corresponding Theme that you want to apply?:0
Setting of Dark Theme Done:)

But running sudo sysmontask gain still shows with light theme

So I tried:
sudo sysmontask.set_dark
Index for Corresponding Theme that you want to apply?:1
Setting of Dark Theme Done:)

But the same, sudo sysmontask still shows up with the light theme

**Comment by KrispyCamel4u** [comment]
> Tried this:
> sudo sysmontask.set_dark
> Index for Corresponding Theme that you want to apply?:0
> Failed to set Theme:(
> Run with sudo(root privileges) is required.
> 
> Tried the same command again because I didn't see it asking for my password before and looked like it worked:
> Index for Corresponding Theme that you want to apply?:0
> Setting of Dark Theme Done:)
> 
> But running sudo sysmontask gain still shows with light theme
> 
> So I tried:
> sudo sysmontask.set_dark
> Index for Corresponding Theme that you want to apply?:1
> Setting of Dark Theme Done:)
> 
> But the same, sudo sysmontask still shows up with the light theme

Hi, on my system(PopOs 20.10) theme setting API works.
What is the list of available themes(which gets list when you run `sudo sysmontask.set_dark`)?
Set it back to default via `sudo sysmontask.set_default`
Try running the below command:
` GTK_THEME=<theme name from the list> sysmontask`
and  then
` sudo GTK_THEME=<theme name from the list> sysmontask`
Let me know the status of these commands.

**Comment by Danny3** [comment]
"What is the list of available themes(which gets list when you run sudo sysmontask.set_dark)?"
It says this:
`[sudo] password for my-username: 
Index for Corresponding Theme that you want to apply?:`
"Set it back to default via sudo sysmontask.set_default"
Done!
`Setting to default: Done:)`

I cannot follow the others as I don't know what the theme names are.

**Comment by Danny3** [comment]
> There is a small bug in `sysmontask.set_dark` API which I have found.
> To resolve your issue for now run `sysmontask.set_light` there you will find the dark theme listed. In my case on Kubuntu VM it was `Breeze-Dark` select that index and it will work with sudo.

True, it worked just as you said !
0 : Breeze
1 : Breeze-Dark
2 : Default
3 : Emacs
4 : Raleigh
Index for Corresponding Theme that you want to apply?:1
Setting of Light Theme Done:)

The message is a bit funny for Breeze-Dark :)

Running sudo sysmontask now opens up with the dark theme and it's great !

Thank you very much !

"The other way of doing this is via KDE settings->Application Style->Configure Gnome/Gtk Application. There you can select any dark theme for the GTK3 application."

I knew about this and I had it configured as Breeze dark before, but on recent KDE Plasma version I cannot find this theme in the drop-down menu and now I'm running the beta version for the next Plasma release (5.22).

I think I might have to ask the KDE Plasma developers on what they did since I cannot find it anymore.

**Comment by KrispyCamel4u** [comment]
Hey, the new release is out with this bug fixed.
