### ISSUE TITLE
Possibility to run as non-root

### ISSUE THREAD

**Issue by j123b567** [KrispyCamel4u/SysMonTask#6]
Running complex program as root is not good decision, because it can do odd things with your system without user knowledge or at least asking. (like [installing unwanted software outside package manager](https://github.com/j123b567/SysMonTask/blob/master/sysmontask/sysmontask.py#L18), which is very very bad idea, ...)

I tried to run the program with `fakeroot` and many features works as expected, so there could be at least two modes or small utility program running with pkexec, which communicates with the main gui and which can be run on demand.

**Comment by jirib** [comment]
One could use dbus/policykit (polkit) to get privileged to kill processes running under different users, see https://www.freedesktop.org/software/polkit/docs/0.105/polkit-apps.html

**Comment by RDKRACZ** [comment]
Every other task manager I have used only asks for a root password when required. Typing root password just to see memory usage in GUI isn't good at all.

**Comment by jirib** [comment]
> Every other task manager I have used only asks for a root password when required. Typing root password just to see memory usage in GUI isn't good at all.

If it would use policykit it won't need to ask root password at all, it would depend on policykit rules. See https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-security-policykit.html. For example if a user would be in 'wheel' group it could work without any password...

**Comment by KrispyCamel4u** [comment]
Actually, this is being worked upon to use it without root also. As soon as it is ready other bugs fix I will let you know.

**Comment by KrispyCamel4u** [comment]
hi all,
The new release has been published. It can now be run as non-root. Please update me from your side :)
