### ISSUE TITLE
Ubuntu hirsute release does not have a release file

### ISSUE THREAD

**Issue by Seltonu** [KrispyCamel4u/SysMonTask#65]
Updated to 21.04, now cannot run "sudo apt update && sudo apt upgrade" as it errors out upon checking the sysmontask ppa.

![image](https://user-images.githubusercontent.com/10287568/122760142-a35d9280-d24f-11eb-98d2-056fd0161873.png)

**Comment by KrispyCamel4u** [comment]
Hi,
As of now it is not updated for new release 21.10. but yeah when the next release of sysmontask comes it will be made available for 21.10 also.

**Comment by KrispyCamel4u** [comment]
#76

**Comment by KrispyCamel4u** [comment]
it is finally has come for 21.04 also.

**Comment by Seltonu** [comment]
Thank you for this release! And thank you for your hard work :)
