### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by lylythechosenone** [KrispyCamel4u/SysMonTask#67]
A dark mode for this would be cool.

**Comment by throwawayaccount1226** [comment]
> A dark mode for this would be cool.

Sysmontask doesn't have native themes. It just uses your system's theme. Change that to a dark one(how you do that is gonna vary based on your desktop environment.

**Comment by lylythechosenone** [comment]
Oh, thanks! I just realized I didn't have a gtk theme enabled, lol.
