### ISSUE TITLE
Disk Read and Write columns show NA

### ISSUE THREAD

**Issue by rambo919** [KrispyCamel4u/SysMonTask#71]
![Screenshot from 2021-07-11 08-06-58](https://user-images.githubusercontent.com/15326328/125184591-53a33300-e21f-11eb-9c56-c59f4f062258.png)

Mix of ext4 and ntfs partitions
Linux Mint 20.2
sysmontask 1.3.9

**Comment by KrispyCamel4u** [comment]
Hi, it not a bug. 
For getting the other user process disk activities higher privileges are required.
So if you run it as a root user you would be able to see this.
More details here: [https://github.com/KrispyCamel4u/SysMonTask#installation](url)
