### ISSUE TITLE
Wrong git tag version

### ISSUE THREAD

**Issue by tobiasbaehr** [KrispyCamel4u/SysMonTask#78]
The lastest release was accidentally tagged with v1.x.x.

This project follows semantic versioning.

I believe you added new features, therefore the version/git tag should be v1.4.0.

With just bugfixes v1.3.10.

**Comment by KrispyCamel4u** [comment]
yes with semantic versioning.
But I have done it this way knowingly. This is the last release for v1.
With v2 the versioning will continue.
