### ISSUE TITLE
It crashes when run under WSL

### ISSUE THREAD

**Issue by DavidXanatos** [KrispyCamel4u/SysMonTask#89]
sudo sysmontask
5.5.1
warning[critical]: psutil>=5.7.2 needed(system-wide)

(sysmontask:12689): Gtk-WARNING **: 13:40:18.150: Error loading theme icon 'media-record' for stock: Icon 'media-record' not present in theme Yaru
color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)}
cpuInit
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 11, in <module>
    load_entry_point('sysmontask===1.x.x', 'console_scripts', 'sysmontask')()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 1127, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 185, in __init__
    self.cpuInit()
  File "/usr/lib/python3/dist-packages/sysmontask/cpu.py", line 96, in cpuInit
    self.cpuMxSpeedLabelValue.set_text('{:.2f} GHz'.format(self.speed[2]/1000))
TypeError: 'NoneType' object is not subscriptable

**Comment by KrispyCamel4u** [comment]
> sudo sysmontask 5.5.1 warning[critical]: psutil>=5.7.2 needed(system-wide)
> 
> (sysmontask:12689): Gtk-WARNING **: 13:40:18.150: Error loading theme icon 'media-record' for stock: Icon 'media-record' not present in theme Yaru color prifile in the setting {'cpu': (0.384, 0.749, 1.0), 'memory': (0.627, 0.196, 0.788), 'disk': (0.109, 0.67, 0.0588), 'network': (0.709, 0.164, 0.164), 'gpu': (0.384, 0.749, 1.0)} cpuInit Traceback (most recent call last): File "/usr/bin/sysmontask", line 11, in load_entry_point('sysmontask===1.x.x', 'console_scripts', 'sysmontask')() File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 1127, in start main=myclass() File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 185, in **init** self.cpuInit() File "/usr/lib/python3/dist-packages/sysmontask/cpu.py", line 96, in cpuInit self.cpuMxSpeedLabelValue.set_text('{:.2f} GHz'.format(self.speed[2]/1000)) TypeError: 'NoneType' object is not subscriptable

Hi...
This is because on wsl one of the dependency is not satisfied. The `psutil`>=5.7.2. update the psutil using the pip and it will work if the GUI is supported on WSL.

**Comment by DavidXanatos** [comment]
indeed, that was it, thanks
